fix: use setup-node step for caching
reside-eng/npm-dependency-stats-action pull request #337
Opened 2021-11-24 21:48 UTC by prescottprue

* Switch to using node-setup for npm caching
* Drops usage of matrix
* Prevent swallowing of test errors as part of reporting step

2021-11-24 21:48 UTC, prescottprue commented on .github/workflows/verify.yml
> +      - name: Comment + Report Coverage
Using our own custom action for comment/upload of coverage

2021-11-24 21:49 UTC, prescottprue commented on dist/licenses.txt
> -The MIT License (MIT)
Not sure why this was removed in a rebuild - it appears that is another copy of it just below, but maybe @actions/io changed their license?

2021-11-24 21:50 UTC, prescottprue commented on jest.config.js
> +  coverageThreshold: {
Will fail builds for us dropping coverage - in prep for when we drop Codecov

2021-11-30 20:49 UTC, hershmire requested changes

2021-11-30 20:49 UTC, hershmire commented on .github/dependabot.yml
> +      include: scope
This is duplicated above and also incorrect. The intention is for `prefix: fix` and `prefix-development: chore` so dependencies are considered releasable by semantic release.

```suggestion
```

2021-11-30 20:49 UTC, hershmire commented on .github/workflows/release.yml
> +  group: release
Just want to confirm that this wouldn't be affected if there were other library workflows with this same group name correct?

2021-11-30 20:49 UTC, hershmire commented on .github/workflows/release.yml
> +  NODE_VERSION: 14.x
Should move up to Node 16.

2021-11-30 20:49 UTC, hershmire commented on .github/workflows/release.yml
> +        uses: actions/setup-node@v2.4.0
Looks like you're downgrading here.

2021-11-30 20:49 UTC, hershmire commented on .github/workflows/verify.yml
> +      - name: Checkout Code
```suggestion
      - name: Checkout code
```

2021-11-30 20:49 UTC, hershmire commented on .github/workflows/verify.yml
> +        uses: actions/checkout@v2.3.4
Downgrading here as well. Looks lie you have some copy/paste issues.

2021-11-30 20:53 UTC, prescottprue commented on .github/dependabot.yml
> +      include: scope
This is to do the same for github-actions - even after this setting was applied i was still seeing PRs from dependabot for github actions having the wrong config. I went with `prefix: chore` because updates to CI action versions shouldn't cause a minor bump, just a patch. This will make sure that these are also part of the release notes

Are you saying to leave as is so that these aren't included in the release notes?

2021-11-30 20:54 UTC, prescottprue commented on .github/workflows/release.yml
> +  NODE_VERSION: 14.x
I was going to capture that in a separate PR so we didn't do too much all at once, but agreed we should

2021-12-07 19:56 UTC, prescottprue commented on .github/workflows/release.yml
> +  group: release
You mean for this same library or other libraries? `concurrency` setting is specific to repo

2021-12-07 23:20 UTC, hershmire commented on .github/dependabot.yml
> +      include: scope
`chore` will not be added to the release notes. Only `feat`, `fix`, and `perf` "releasable" commits. I don't think we need to make Github Action upgrades releasable because it shouldn't affect the application code. In the rare circumstances that it does, we can modify the commit type before merging the PR.

2021-12-07 23:44 UTC, prescottprue commented on .github/dependabot.yml
> +      include: scope
Changed

2021-12-08 23:23 UTC, merged